"""Canonical names and sex seeds for the 74 registered certificate animals.

Sex is a *seed* only. The graph overwrites it when an animal appears as
sire or dam. Seeds exist because the youngest generation never appears
as a parent in this certificate set, and the AOA title line does not
carry sex.
"""

from __future__ import annotations

# filename prefix → (display name, sex seed or None)
# Prefix must uniquely match the start of the cert_lineage filename.
REGISTERED: list[tuple[str, str, str | None]] = [
    ("4-SIGHTS_HOLIDAY", "4-SIGHT'S HOLIDAY", "F"),
    ("5CS_CAPTAIN_CHAOS", "5C'S CAPTAIN CHAOS", "M"),
    ("5CS_CHANTERELLA", "5C'S CHANTERELLA", "F"),
    ("APP_OSA_PHRENCH_BRAID", "APP OSA PHRENCH BRAID", "F"),
    ("APP_PHORCE_PHACTOR", "APP PHORCE PHACTOR", "M"),
    ("APP_WILD_PHLOX", "APP WILD PHLOX", "F"),
    ("ARAPAHO_DELGADOS_ILLYAPA", "ARAPAHO DELGADO'S ILLYAPA", "M"),
    ("BOMBERS_DIAMOND_LIL", "BOMBER'S DIAMOND LIL", "F"),
    ("CIRCLE_CLIFFS_MELVIN", "CIRCLE CLIFF'S MELVIN", "M"),
    ("CIRCLE_CLIFFS_SWEET_CAROLINE", "CIRCLE CLIFF'S SWEET CAROLINE", "F"),
    ("CRESCENT_MOONS_KEMMAUS", "CRESCENT MOON'S KEMMAUS", "M"),
    ("CRYSTAL_MOCHACCINO", "CRYSTAL MOCHACCINO", "F"),
    ("CRYSTAL_ROYAL_GOLDS_MACKINAW", "CRYSTAL ROYAL GOLD'S MACKINAW", "M"),
    ("ESTATES_LA_PRESTIGE_CRIMSON", "ESTATES LA PRESTIGE CRIMSON", "F"),
    ("G-TRIBES_ROCKYS_ASH", "G-TRIBE'S ROCKY'S ASH", "M"),
    ("HEAVENS_HILL_PERUVIAN_CELESTIA", "HEAVEN'S HILL PERUVIAN CELESTIA", "F"),
    ("HERITAGE_SILVER_PROMISE", "HERITAGE SILVER PROMISE", "F"),
    ("HMAFS_AIRGEAD", "HMAF'S AIRGEAD", "M"),
    ("HOWLING_HILL_SING_THE_BODY_ELECTRIC", "HOWLING HILL SING THE BODY ELECTRIC", "F"),
    ("IRISH_MEADOWS_TAYT", "IRISH MEADOWS TAYT", "F"),
    ("LIBERTYALPACAS_SMOKE_SCREEN", "LIBERTYALPACAS SMOKE SCREEN", "M"),
    ("MAMGB_NATAN_SAPA", "MAMGB NATAN SAPA", "M"),
    ("MARYS_SIQUANI_BELLE", "MARY'S SIQUANI BELLE", "F"),
    ("MISS_ALOHA", "MISS ALOHA MOONSHINE", "F"),
    ("MISS_AUTARY", "MISS AUTARY", "F"),
    ("MTAR_ORLANDO_CLOUDS_MCDREAMY", "MTAR ORLANDO CLOUD'S MCDREAMY", "M"),
    ("MTAR_PHASMA", "MTAR PHASMA", "F"),
    ("NOBLE_AMARETTO", "NOBLE AMARETTO", "F"),
    ("PALLATONS_KALIBAUT_ALYST", "PALLATON'S KALIBAUT ALYST", "M"),
    ("PARAGONS_ESMERALDA", "PARAGON'S ESMERALDA", "F"),
    ("PATAGONIAS_DUSTY", "PATAGONIA'S DUSTY", "F"),
    ("PATAGONIAS_NERUDA", "PATAGONIA'S NERUDA", "M"),
    ("PHPC_ARTILLERY", "PHPC ARTILLERY", "M"),
    ("RED_GRANITES_AFTERSHOCK", "RED GRANITES AFTERSHOCK", "F"),
    ("RED_GRANITES_ALYDAR", "RED GRANITES ALYDAR", "M"),
    ("RED_GRANITES_BRAVEHEART", "RED GRANITES BRAVEHEART", "M"),
    ("RED_GRANITES_JAFFA", "RED GRANITES JAFFA", "F"),
    ("RED_GRANITES_JENGA", "RED GRANITES JENGA", "F"),
    ("RED_GRANITES_JEZEBELL", "RED GRANITES JEZEBELL", "F"),
    ("RED_GRANITES_PRIM_PROPER", "RED GRANITES PRIM & PROPER", "F"),
    ("RGR_J_USTIFICATION", "RGR JUSTIFICATION", "F"),
    ("RGR_JIGSAW", "RGR JIGSAW", "F"),
    ("RGRS_MISS_CONTRARY", "RGR'S MISS CONTRARY", "F"),
    ("ROYAL_DIAMANTES_JEWEL", "ROYAL DIAMANTE'S JEWEL", "F"),
    ("RR_PALOMA_PICASSO", "RR PALOMA PICASSO", "F"),
    ("RR_SARAH_VAUGHN", "RR SARAH VAUGHN", "F"),
    ("RR_WONDER_WOMAN", "RR WONDER WOMAN", "F"),
    ("SCA_PERUVIAN_SILVERBELLE", "SCA PERUVIAN SILVERBELLE", "F"),
    ("SCS_CARRINGTON", "SC'S CARRINGTON", "F"),
    ("SCS_CHARENTE", "SC'S CHARENTE", "F"),
    ("SCS_CLARKIA", "SC'S CLARKIA", "F"),
    ("SCS_CRICKIT", "SC'S CRICKIT", "F"),
    ("SMOKIN_HAUTE", "SMOKIN HAUTE", "F"),
    ("SNOWMASS_ALLURING_XX", "SNOWMASS ALLURING XX", "F"),
    ("SNOWMASS_CONOPA_XXX", "SNOWMASS CONOPA XXX", "M"),
    ("SNOWMASS_ENCHANTED_TOUCH", "SNOWMASS ENCHANTED TOUCH", "F"),
    ("SNOWMASS_IRON_MAIDEN", "SNOWMASS IRON MAIDEN", "F"),
    ("SNOWMASS_MAJESTIC_REFLECTION", "SNOWMASS MAJESTIC REFLECTION", "M"),
    ("SNOWMASS_MATRIX", "SNOWMASS MATRIX", "M"),
    ("SNOWMASS_MIDNIGHT_GAZE", "SNOWMASS MIDNIGHT GAZE", "F"),
    ("SNOWMASS_SIMPLY_SMOKIN", "SNOWMASS SIMPLY SMOKIN", "F"),
    ("SNOWMASS_SMOKIN_WAVES", "SNOWMASS SMOKIN WAVES", "M"),
    ("SPARTANS_SILVER-LINING", "SPARTAN'S SILVER-LINING", "M"),
    ("SSAFL_MICHELANGELOS_PERUVIAN_CUPID", "SSAFL MICHELANGELO'S PERUVIAN CUPID", "M"),
    ("SUNNYHILLS_ZANGS_BALTAZAR", "SUNNYHILL'S ZANG'S BALTAZAR", "M"),
    ("TCB_CORKY", "TCB CORKY", "M"),
    ("THATLL_DO_BLACKBEARDS_BOOTY", "THAT'LL DO BLACKBEARD'S BOOTY", "F"),
    ("THOR_FARMS_LOOKING_GLASS", "THOR FARMS LOOKING GLASS", "F"),
    ("VINTAGE_CASHMERES_U-TAUPE-IA", "VINTAGE CASHMERE'S U-TAUPE-IA", "F"),
    ("WILLOWWIND_ECHO_DELTA", "WILLOWWIND ECHO DELTA", "F"),
    ("WILLOWWIND_INSPIRATION", "WILLOWWIND INSPIRATION", "F"),
    ("WILLOWWIND_SHOGUN", "WILLOWWIND SHOGUN", "M"),
    ("WILLOWWIND_SL_HALO", "WILLOWWIND SL HALO", "F"),
    ("WILLOWWIND_THE_SHAMAN", "WILLOWWIND THE SHAMAN", "M"),
]


def lookup_registered(filename: str) -> tuple[str, str | None] | None:
    stem = filename.rsplit(".", 1)[0]
    hits = [row for row in REGISTERED if stem.startswith(row[0])]
    if not hits:
        return None
    hits.sort(key=lambda r: len(r[0]), reverse=True)
    return hits[0][1], hits[0][2]


# Famous ancestors we want stable short names for in the desk.
FAMOUS_ALIASES = {
    "PERUVIAN HEMINGWAY G171": "HEMINGWAY",
    "4PERUVIAN LEGACY 6016": "PERUVIAN LEGACY",
    "SNOWMASS MATRIX": "SNOWMASS MATRIX",
    "SNOWMASS CONOPA XXX": "SNOWMASS CONOPA XXX",
    "SNOWMASS XXXTREME": "SNOWMASS XXXTREME",
    "SNOWMASS LEGACY GOLD": "SNOWMASS LEGACY GOLD",
    "AUSSIE GUNS N ROSES": "AUSSIE GUNS-N-ROSES",
    "AUSSIE 38 SPECIAL": "AUSSIE .38 SPECIAL",
}
